version: "3.5"

volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/${USER}/data/wordpress
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: /home/${USER}/data/mariadb
                        o: bind
                        type: none

networks:
  inception:
    name: inception

services:
  nginx:
    build:
      dockerfile: ./requirements/nginx/Dockerfile
    container_name: nginx
    env_file:
      - ./.env
    volumes:
      - wordpress:/var/www/html/wordpress
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    image: wordpress:42
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html/wordpress
    env_file:
      - .env
    networks:
      - inception
    restart: always
  mariadb:
    build:
      dockerfile: ./requirements/mariadb/Dockerfile
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - ./.env
    expose:
      - "3306:3306"
    restart: always
